# Generated by Django 2.2.4 on 2019-11-10 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('add_user_staff', 'Can add a staff Member'), ('delete_user_staff', 'Can remove a staff Member'), ('update_user_staff', 'Can update a staff Member'), ('add_manager_staff', 'Can add a Line Manager'), ('delete_manager_staff', 'Can remove a Line Manager'), ('update_manager_staff', 'Can update a Line Manager'), ('add_admin_staff', 'Can add an Admin'), ('delete_admin_staff', 'Can remove an Admin'), ('update_admin_staff', 'Can update an Admin'), ('add_department', 'Can add a Departnment'), ('delete_department', 'Can remove a Departnment'), ('update_department', 'Can update a Departnment'), ('assign_manager_department', 'Can assign a manager for a Departnment'), ('remover_manager_departmet', 'Can remove a manager from a Department'), ('add_review_area', 'Can add an area for the employee review'), ('edit_review_area', 'Can edit an area for the employee review'), ('delete_review_area', 'Can delete an area for the employee review'), ('add_indicator_item', 'Can add an indicator for the employee review'), ('edit_indicator_item', 'Can edit an indicatorindicator for the employee review'), ('delete_indicator_item', 'Can delete an indicator for the employee review'), ('close_task', 'Can remove a task by setting its status as closed')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'staff'), (3, 'staff'), (1, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile/')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
