# Generated by Django 2.2.4 on 2019-11-19 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('line_manager_score', models.FloatField(default=0)),
                ('staff_score', models.FloatField(default=0)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KPIs.Area')),
            ],
            options={
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KPIs.Area')),
                ('indicators', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KPIs.Indicators')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_average', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPIs.Area')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
