# Generated by Django 2.2.7 on 2019-11-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='line_manager_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicators',
            name='staff_score',
            field=models.FloatField(default=0),
        ),
    ]
