# Generated by Django 2.2.7 on 2019-11-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KPIs', '0002_auto_20191114_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicators',
            options={'ordering': ['area']},
        ),
        migrations.AddField(
            model_name='score',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KPIs.Indicators'),
        ),
    ]
