# Generated by Django 2.2.7 on 2019-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPIs', '0003_auto_20191115_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='indicator',
            new_name='indicators',
        ),
    ]
