# Generated by Django 2.2.4 on 2019-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
