# Generated by Django 2.2.4 on 2019-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('line_manager', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='departments',
        ),
    ]
