# Generated by Django 2.2.4 on 2019-11-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Departments', '0002_auto_20191110_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('design_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Weak'), (3, 'Average'), (4, 'Good'), (5, 'Excelent')], default=0)),
                ('userbility_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Weak'), (3, 'Average'), (4, 'Good'), (5, 'Excelent')], default=0)),
                ('content_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Weak'), (3, 'Average'), (4, 'Good'), (5, 'Excelent')], default=0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
