# Generated by Django 2.2.4 on 2019-11-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
