# Generated by Django 2.2.4 on 2019-11-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0004_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='line_manager',
        ),
    ]
